name: Deploy to VM

on:
  push:
    branches: [ "main" ]   # change if your default branch is different

concurrency:
  group: deploy-vm
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -euxo pipefail
            echo "== whoami/host =="
            whoami
            hostname

            echo "== list /home/ubuntu =="
            ls -la /home/ubuntu || true

            echo "== check repo path =="
            ls -ld /home/ubuntu/Discord_Bot || true

            echo "== cd into repo =="
            cd /home/ubuntu/Discord_Bot
            pwd

            echo "== git status/fetch/reset =="
            git rev-parse --is-inside-work-tree
            git fetch origin main
            git reset --hard origin/main

            echo "== install deps if requirements.txt exists =="
            if [ -f requirements.txt ]; then /home/ubuntu/Discord_Bot/.venv/bin/pip install -r requirements.txt; fi

            echo "== restart service =="
            sudo systemctl restart discordbot

            echo "== service status =="
            sudo systemctl --no-pager --full status discordbot || true

            echo "== journal tail =="
            journalctl -u discordbot -n 50 --no-pager || true

